substitutions:
  name: xiaomi-philips-light
  device_description: "Xiaomi Philips Zhirui Light"
  external_components_source: github://syssi/esphome-xiaomi-philips-light@main

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-xiaomi-philips-light"
    version: 2.0.0

esp8266:
  board: esp_wroom_02

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG

api:

light:
  - platform: xiaomi_light
    name: "${name}"
    id: bulb
    cold_white: output_cw
    brightness: output_brightness
    gamma_correct: 0
    default_transition_length: 350ms

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_cw
  - platform: esp8266_pwm
    pin: GPIO15
    id: output_brightness

sensor:
  - platform: ntc
    name: "${name} ntc temperature"
    sensor: resistance0
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100000

  - platform: resistance
    name: "${name} resistance"
    id: resistance0
    internal: true
    sensor: adc0
    configuration: DOWNSTREAM
    resistor: 500000
    reference_voltage: 3.3

  - platform: adc
    name: "${name} adc"
    id: adc0
    internal: true
    pin: A0
    update_interval: 60s
    filters:
      - median:
          window_size: 3
          send_every: 1
          send_first_at: 1
