substitutions:
  name: xiaomi-philips-light
  device_description: "Xiaomi Philips Zhirui Light"

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-xiaomi-philips-light"
    version: 1.1.0
  includes:
    - xiaomi_light.h
  on_boot:
      priority: 600
      then:
        - light.turn_on:
            id: bulb

esp8266:
  board: esp_wroom_02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG

api:

light:
  - platform: custom
    lambda: |-
      auto light_out = new XiaomiLight(id(output_cw),id(output_ww));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: ${name}
        id: bulb
        gamma_correct: 0
        default_transition_length: 350ms

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_cw
  - platform: esp8266_pwm
    pin: GPIO15
    id: output_ww

sensor:
  - platform: ntc
    name: "${name} ntc temperature"
    sensor: resistance0
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100000

  - platform: resistance
    name: "${name} resistance"
    id: resistance0
    internal: true
    sensor: adc0
    configuration: DOWNSTREAM
    resistor: 500000
    reference_voltage: 3.3

  - platform: adc
    name: "${name} adc"
    id: adc0
    internal: true
    pin: A0
    update_interval: 60s
    filters:
      - median:
          window_size: 3
          send_every: 1
          send_first_at: 1
