substitutions:
  hostname: xiaomi-philips-light

esphome:
  name: $hostname
  platform: ESP8266
  board: esp_wroom_02
  includes: 
    - xiaomi_light.h

web_server:
  port: 80

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: out_cw
  - platform: esp8266_pwm
    pin: GPIO15
    id: out_b

light:
  - platform: custom 
    lambda: |- 
      auto light_out = new XiaomiLight(id(out_cw),id(out_b)); 
      App.register_component(light_out); 
      return {light_out}; 
    lights: 
      - name: $hostname Light
        id: TheLight
        gamma_correct: 0

sensor:
  - platform: ntc
    id: the_ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100000
    name: "$hostname NTC Temperature"
    on_value:
      if:
        condition:
          light.is_on: TheLight
        then:
          lambda: |-
            float brt; 
            id(TheLight).current_values_as_brightness(&brt);
            if (x > 55) {
              brt -= 0.1;
              auto cl = id(TheLight).turn_on();
              cl.set_brightness(brt);
              cl.perform();
              ESP_LOGD("NTC", "Overheat! Decreasing brightness to %f", brt);
            }
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 500000
    reference_voltage: 3.3
    name: $hostname Resistance Sensor
    internal: true
  - platform: adc
    name: "$hostname RAW ADC"
    internal: true
    id: source_sensor
    pin: A0
    update_interval: 60s
    filters:
      - median:
          window_size: 3
          send_every: 1
          send_first_at: 1
